# Generated by Django 4.2.3 on 2023-12-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_member_user_alter_member_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
